### ISSUE TITLE
TimeScaleDb container

### ISSUE THREAD

**Issue by vikrambosevibrent** [testcontainers/testcontainers-python#126]
TimeScaleDb Container not available. is that any plan to add that? Thanks

**Comment by tillahoffmann** [comment]
Not planned at the moment, but PRs are welcome.

**Comment by vikrambosevibrent** [comment]
sure.. Will do that..

**Comment by pffijt** [comment]
It wouldn't be necessary to create a separate module/client for a TimescaleDB container since TimescaleDB is just an extension on top of PostgreSQL [(see here)](https://docs.timescale.com/getting-started/latest/#what-is-timescaledb).  Users of the TimescaleDB container can make use of PostgresDB container client.

Example:
```python
timescaled_container = PostgresContainer('timescale/timescaledb:latest-pg12')

with timescaled_container as timescaled:
    e = sqlalchemy.create_engine(timescaled.get_connection_url())
    e.execute('''
        CREATE TABLE stocks_real_time (
          time TIMESTAMPTZ NOT NULL,
          symbol TEXT NOT NULL,
          price DOUBLE PRECISION NULL,
          day_volume INT NULL
        ); 
    ''')

    e.execute('''
        SELECT create_hypertable('stocks_real_time','time');
    ''')
```

**Comment by pffijt** [comment]
I think we can close this issue :)
