### ISSUE TITLE
Support passing custom env-file? 

### ISSUE THREAD

**Issue by kvalv** [testcontainers/testcontainers-python#134]
Hi,

I came across this library and it seems very useful for running integration tests. My current `docker-compose.yml` make use of the `.env` file to pass in various environment variables. However, for integration tests I want to use a different `.env` file. Using docker-compose from the shell I can just do `docker-compose --env-file .env_test up`.

Would it be possible to support a `env_file` argument in `compose.DockerCompose.__init__` which defaults to `.env` but can be set to something else? That would help me alot, because the only alternative I see is to make a second docker-compose.yml file and specify a separate [env_file for each service](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) which is not very pretty.

**Comment by tillahoffmann** [comment]
Yes, that should be possible by modifying https://github.com/testcontainers/testcontainers-python/blob/bc969c53680606d7fff6a2e8350f5a6f234fcd38/testcontainers/compose.py#L82-L87

Contributions welcome!

**Comment by Petrosyuk** [comment]
Hey - I can tackle this. I've been looking to contribute to open source. Will write an implementation and tests. 
I think it is best to include the env tag here instead of start: 

https://github.com/testcontainers/testcontainers-python/blob/bc969c53680606d7fff6a2e8350f5a6f234fcd38/testcontainers/compose.py#L76-L80

**Comment by tillahoffmann** [comment]
Closed in #135.
